// Generated by Copilot

import java

/**
 * This query identifies annotations of type `SuppressWarnings` with the value "PMD".
 * It selects these annotations and provides a message to avoid removing PMD warnings
 * or to document clearly why they are not applicable.
 */
from Annotation ann, AnnotationType anntp
where 
    anntp = ann.getType() and
    anntp.hasQualifiedName("java.lang", "SuppressWarnings") and
    exists(CompileTimeConstantExpr expr |
        ann.getValue("value").(Exprs).getAnExpr() = expr and
        expr.getStringValue().toUpperCase() = "PMD"
    )
select ann, "Avoid removing PMD warnings, or document clearly why they are not applicable."